App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [create, update]
    longitude:
        - Range:
            min: -180
            max: 180
            groups: [create, update]

App\Entity\Measurement:
  properties:
    temperature:
      - Range:
          min: -273.15
          max: 1000
          groups: [create, update]
    humidity:
      - Range:
          min: 0
          max: 100
          groups: [create, update]
